// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorCountMessage.proto

package edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf;

public final class SensorCountMessage {
  private SensorCountMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public static final class SensorEntry extends
      com.google.protobuf.GeneratedMessageLite {
    // Use SensorEntry.newBuilder() to construct.
    private SensorEntry() {
      initFields();
    }
    private SensorEntry(boolean noInit) {}
    
    private static final SensorEntry defaultInstance;
    public static SensorEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public SensorEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // required int64 count = 1;
    public static final int COUNT_FIELD_NUMBER = 1;
    private boolean hasCount;
    private long count_ = 0L;
    public boolean hasCount() { return hasCount; }
    public long getCount() { return count_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasCount) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCount()) {
        output.writeInt64(1, getCount());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getCount());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry, Builder> {
      private edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry result;
      
      // Construct using edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry();
        return builder;
      }
      
      protected edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry getDefaultInstanceForType() {
        return edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry other) {
        if (other == edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry.getDefaultInstance()) return this;
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              setCount(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // required int64 count = 1;
      public boolean hasCount() {
        return result.hasCount();
      }
      public long getCount() {
        return result.getCount();
      }
      public Builder setCount(long value) {
        result.hasCount = true;
        result.count_ = value;
        return this;
      }
      public Builder clearCount() {
        result.hasCount = false;
        result.count_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorEntry)
    }
    
    static {
      defaultInstance = new SensorEntry(true);
      edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorEntry)
  }
  
  public static final class AppEntry extends
      com.google.protobuf.GeneratedMessageLite {
    // Use AppEntry.newBuilder() to construct.
    private AppEntry() {
      initFields();
    }
    private AppEntry(boolean noInit) {}
    
    private static final AppEntry defaultInstance;
    public static AppEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public AppEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // required uint32 uid = 1;
    public static final int UID_FIELD_NUMBER = 1;
    private boolean hasUid;
    private int uid_ = 0;
    public boolean hasUid() { return hasUid; }
    public int getUid() { return uid_; }
    
    // required string pkgName = 2;
    public static final int PKGNAME_FIELD_NUMBER = 2;
    private boolean hasPkgName;
    private java.lang.String pkgName_ = "";
    public boolean hasPkgName() { return hasPkgName; }
    public java.lang.String getPkgName() { return pkgName_; }
    
    // required uint64 lastUpdate = 3;
    public static final int LASTUPDATE_FIELD_NUMBER = 3;
    private boolean hasLastUpdate;
    private long lastUpdate_ = 0L;
    public boolean hasLastUpdate() { return hasLastUpdate; }
    public long getLastUpdate() { return lastUpdate_; }
    
    // repeated .edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorEntry sensorEntry = 4;
    public static final int SENSORENTRY_FIELD_NUMBER = 4;
    private java.util.List<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry> sensorEntry_ =
      java.util.Collections.emptyList();
    public java.util.List<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry> getSensorEntryList() {
      return sensorEntry_;
    }
    public int getSensorEntryCount() { return sensorEntry_.size(); }
    public edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry getSensorEntry(int index) {
      return sensorEntry_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasUid) return false;
      if (!hasPkgName) return false;
      if (!hasLastUpdate) return false;
      for (edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry element : getSensorEntryList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasUid()) {
        output.writeUInt32(1, getUid());
      }
      if (hasPkgName()) {
        output.writeString(2, getPkgName());
      }
      if (hasLastUpdate()) {
        output.writeUInt64(3, getLastUpdate());
      }
      for (edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry element : getSensorEntryList()) {
        output.writeMessage(4, element);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasUid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getUid());
      }
      if (hasPkgName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPkgName());
      }
      if (hasLastUpdate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, getLastUpdate());
      }
      for (edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry element : getSensorEntryList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry, Builder> {
      private edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry result;
      
      // Construct using edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry();
        return builder;
      }
      
      protected edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry getDefaultInstanceForType() {
        return edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.sensorEntry_ != java.util.Collections.EMPTY_LIST) {
          result.sensorEntry_ =
            java.util.Collections.unmodifiableList(result.sensorEntry_);
        }
        edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry other) {
        if (other == edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasPkgName()) {
          setPkgName(other.getPkgName());
        }
        if (other.hasLastUpdate()) {
          setLastUpdate(other.getLastUpdate());
        }
        if (!other.sensorEntry_.isEmpty()) {
          if (result.sensorEntry_.isEmpty()) {
            result.sensorEntry_ = new java.util.ArrayList<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry>();
          }
          result.sensorEntry_.addAll(other.sensorEntry_);
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              setUid(input.readUInt32());
              break;
            }
            case 18: {
              setPkgName(input.readString());
              break;
            }
            case 24: {
              setLastUpdate(input.readUInt64());
              break;
            }
            case 34: {
              edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry.Builder subBuilder = edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSensorEntry(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required uint32 uid = 1;
      public boolean hasUid() {
        return result.hasUid();
      }
      public int getUid() {
        return result.getUid();
      }
      public Builder setUid(int value) {
        result.hasUid = true;
        result.uid_ = value;
        return this;
      }
      public Builder clearUid() {
        result.hasUid = false;
        result.uid_ = 0;
        return this;
      }
      
      // required string pkgName = 2;
      public boolean hasPkgName() {
        return result.hasPkgName();
      }
      public java.lang.String getPkgName() {
        return result.getPkgName();
      }
      public Builder setPkgName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPkgName = true;
        result.pkgName_ = value;
        return this;
      }
      public Builder clearPkgName() {
        result.hasPkgName = false;
        result.pkgName_ = getDefaultInstance().getPkgName();
        return this;
      }
      
      // required uint64 lastUpdate = 3;
      public boolean hasLastUpdate() {
        return result.hasLastUpdate();
      }
      public long getLastUpdate() {
        return result.getLastUpdate();
      }
      public Builder setLastUpdate(long value) {
        result.hasLastUpdate = true;
        result.lastUpdate_ = value;
        return this;
      }
      public Builder clearLastUpdate() {
        result.hasLastUpdate = false;
        result.lastUpdate_ = 0L;
        return this;
      }
      
      // repeated .edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorEntry sensorEntry = 4;
      public java.util.List<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry> getSensorEntryList() {
        return java.util.Collections.unmodifiableList(result.sensorEntry_);
      }
      public int getSensorEntryCount() {
        return result.getSensorEntryCount();
      }
      public edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry getSensorEntry(int index) {
        return result.getSensorEntry(index);
      }
      public Builder setSensorEntry(int index, edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.sensorEntry_.set(index, value);
        return this;
      }
      public Builder setSensorEntry(int index, edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry.Builder builderForValue) {
        result.sensorEntry_.set(index, builderForValue.build());
        return this;
      }
      public Builder addSensorEntry(edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.sensorEntry_.isEmpty()) {
          result.sensorEntry_ = new java.util.ArrayList<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry>();
        }
        result.sensorEntry_.add(value);
        return this;
      }
      public Builder addSensorEntry(edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry.Builder builderForValue) {
        if (result.sensorEntry_.isEmpty()) {
          result.sensorEntry_ = new java.util.ArrayList<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry>();
        }
        result.sensorEntry_.add(builderForValue.build());
        return this;
      }
      public Builder addAllSensorEntry(
          java.lang.Iterable<? extends edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry> values) {
        if (result.sensorEntry_.isEmpty()) {
          result.sensorEntry_ = new java.util.ArrayList<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorEntry>();
        }
        super.addAll(values, result.sensorEntry_);
        return this;
      }
      public Builder clearSensorEntry() {
        result.sensorEntry_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.AppEntry)
    }
    
    static {
      defaultInstance = new AppEntry(true);
      edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.AppEntry)
  }
  
  public static final class SensorCounter extends
      com.google.protobuf.GeneratedMessageLite {
    // Use SensorCounter.newBuilder() to construct.
    private SensorCounter() {
      initFields();
    }
    private SensorCounter(boolean noInit) {}
    
    private static final SensorCounter defaultInstance;
    public static SensorCounter getDefaultInstance() {
      return defaultInstance;
    }
    
    public SensorCounter getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated .edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.AppEntry appEntry = 1;
    public static final int APPENTRY_FIELD_NUMBER = 1;
    private java.util.List<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry> appEntry_ =
      java.util.Collections.emptyList();
    public java.util.List<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry> getAppEntryList() {
      return appEntry_;
    }
    public int getAppEntryCount() { return appEntry_.size(); }
    public edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry getAppEntry(int index) {
      return appEntry_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry element : getAppEntryList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry element : getAppEntryList()) {
        output.writeMessage(1, element);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry element : getAppEntryList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter, Builder> {
      private edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter result;
      
      // Construct using edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter();
        return builder;
      }
      
      protected edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter getDefaultInstanceForType() {
        return edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.appEntry_ != java.util.Collections.EMPTY_LIST) {
          result.appEntry_ =
            java.util.Collections.unmodifiableList(result.appEntry_);
        }
        edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter other) {
        if (other == edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.SensorCounter.getDefaultInstance()) return this;
        if (!other.appEntry_.isEmpty()) {
          if (result.appEntry_.isEmpty()) {
            result.appEntry_ = new java.util.ArrayList<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry>();
          }
          result.appEntry_.addAll(other.appEntry_);
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry.Builder subBuilder = edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAppEntry(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.AppEntry appEntry = 1;
      public java.util.List<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry> getAppEntryList() {
        return java.util.Collections.unmodifiableList(result.appEntry_);
      }
      public int getAppEntryCount() {
        return result.getAppEntryCount();
      }
      public edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry getAppEntry(int index) {
        return result.getAppEntry(index);
      }
      public Builder setAppEntry(int index, edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.appEntry_.set(index, value);
        return this;
      }
      public Builder setAppEntry(int index, edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry.Builder builderForValue) {
        result.appEntry_.set(index, builderForValue.build());
        return this;
      }
      public Builder addAppEntry(edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.appEntry_.isEmpty()) {
          result.appEntry_ = new java.util.ArrayList<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry>();
        }
        result.appEntry_.add(value);
        return this;
      }
      public Builder addAppEntry(edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry.Builder builderForValue) {
        if (result.appEntry_.isEmpty()) {
          result.appEntry_ = new java.util.ArrayList<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry>();
        }
        result.appEntry_.add(builderForValue.build());
        return this;
      }
      public Builder addAllAppEntry(
          java.lang.Iterable<? extends edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry> values) {
        if (result.appEntry_.isEmpty()) {
          result.appEntry_ = new java.util.ArrayList<edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.AppEntry>();
        }
        super.addAll(values, result.appEntry_);
        return this;
      }
      public Builder clearAppEntry() {
        result.appEntry_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCounter)
    }
    
    static {
      defaultInstance = new SensorCounter(true);
      edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCountMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:edu.ucla.ee.nesl.privacyfilter.filtermanager.io.protobuf.SensorCounter)
  }
  
  
  static {
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
